audit/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new_link/$', views.new_link, name='new_link'),
    url(r'^new_link_1c/$', views.new_link_1c, name='new_link_1c'),
]

marta/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('audit.urls', namespace='audit')),
]

audit/models.py
from django.db import models


class Link(models.Model):

    text = models.CharField(max_length=200)
    check = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

audit/forms.py
from django import forms

from .models import Link


class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = ['text']
        labels = {'text': ''}

audit/views.py
from django.views.decorators.csrf import csrf_exempt

from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.core.urlresolvers import reverse

from .models import Link
from .forms import LinkForm

from .req_to_1c import Req


def index(request):

    links = Link.objects.order_by('date_added')
    context = {'links': links}

    return render(request, 'audit/index.html', context)


def new_link(request):

    if request.method != 'POST':
        form = LinkForm()
    else:
        form = LinkForm(request.POST)
        if form.is_valid():
            link = form.save()

            link_id = link.id
            text = request.POST['text']

            req = Req(link_id, text)
            req.req_to_1c()

            return HttpResponseRedirect(reverse('audit:index'))
    context = {'form': form}
    return render(request, 'audit/new_link.html', context)


@csrf_exempt
def new_link_1c(request):

    if request.method == 'POST':
        link_id = int(request.POST['link_id'])
        check = request.POST['check']

        link = Link.objects.get(id=link_id)
        link.check = check
        link.save()

        return JsonResponse({'status': 'ok'})

audit/templates/audit/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Audit</title>
  </head>
  <body>
    <h1>Audit!</h1>
    {% block content %}
    {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

audit/templates/audit/index.html
{% extends 'audit/base.html' %}

{% block content %}
<a href="{% url 'audit:new_link' %}">add new link</a>
<ul>
    {% for link in links %}
        <li>{{ link.id }} - {{ link.text }} - {{ link.check }}</li>
    {% empty %}
        <li>no records</li>
    {% endfor %}
</ul>
{% endblock content %}

audit/templates/audit/new_link.html
{% extends 'audit/base.html' %}

{% block content %}
<p>add new link:</p>
<form action="{% url 'audit:new_link' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button name="submit">add link</button>
</form>
{% endblock content %}